# Stage 1 - Build React application
FROM node:14.17.0 as build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Stage 2 - Serve the built React application using a lightweight web server
FROM node:14.17.0-alpine
WORKDIR /app
COPY --from=build /app/build ./build
RUN npm install -g serve
EXPOSE 3000
CMD serve -s build

